### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by lepmik** [rproepp/spykeviewer#10]
Hi, when starting spykeviewer I get the following error. The neo version I have (master @ github) does not have a module description

```
Traceback (most recent call last):
  File "/home/mikkel/.virtualenvs/NEO/bin/spykeviewer", line 9, in <module>
    load_entry_point('spykeviewer==0.4.2', 'gui_scripts', 'spykeviewer')()
  File "/home/mikkel/apps/NEO/spykeviewer/spykeviewer/start.py", line 42, in main
    from ui.main_window_neo import MainWindowNeo
  File "/home/mikkel/apps/NEO/spykeviewer/spykeviewer/ui/main_window_neo.py", line 21, in <module>
    from .main_window import MainWindow
  File "/home/mikkel/apps/NEO/spykeviewer/spykeviewer/ui/main_window.py", line 33, in <module>
    from spykeutils.plot.helper import ProgressIndicatorDialog
  File "/home/mikkel/apps/NEO/spykeutils/spykeutils/plot/__init__.py", line 55, in <module>
    from peri_stimulus_histogram import psth
  File "/home/mikkel/apps/NEO/spykeutils/spykeutils/plot/peri_stimulus_histogram.py", line 8, in <module>
    from .. import rate_estimation
  File "/home/mikkel/apps/NEO/spykeutils/spykeutils/rate_estimation.py", line 7, in <module>
    import signal_processing as sigproc
  File "/home/mikkel/apps/NEO/spykeutils/spykeutils/signal_processing.py", line 6, in <module>
    import tools
  File "/home/mikkel/apps/NEO/spykeutils/spykeutils/tools.py", line 2, in <module>
    import neo.description
ImportError: No module named description
```

**Comment by lepmik** [comment]
When I install neo, spykeutils and spykeviewer from pip everything is OK, however when pulling latest versions from git I get the above described error. Is there a dependency I have overseen between neo and spykeviewer/spykeutils?

**Comment by rproepp** [comment]
This should now be fixed in the current development version of spykeutils.
