### ISSUE TITLE
error with segment name='string'

### ISSUE THREAD

**Issue by lepmik** [rproepp/spykeviewer#12]
Hi, when I name my segment with some string I get:

```
Traceback (most recent call last):
  File "/home/mikkel/apps/NEO/spykeviewer/spykeviewer/ui/neo_navigation.py", line 304, in selected_blocks_changed
    self.populate_neo_segment_list()
  File "/home/mikkel/apps/NEO/spykeviewer/spykeviewer/ui/neo_navigation.py", line 172, in populate_neo_segment_list
    (self.parent.block_ids[s.block], i)
TypeError: unsupported operand type(s) for +: 'numpy.ndarray' and 'str'
Error loading selection:
Traceback (most recent call last):
  File "/home/mikkel/apps/NEO/spykeviewer/spykeviewer/ui/main_window.py", line 778, in load_selections_from_file
    self.set_current_selection(s)
  File "/home/mikkel/apps/NEO/spykeviewer/spykeviewer/ui/main_window_neo.py", line 98, in set_current_selection
    self.set_neo_selection(data)
  File "/home/mikkel/apps/NEO/spykeviewer/spykeviewer/ui/main_window_neo.py", line 387, in set_neo_selection
    self.neoNavigationDock.set_selection(data)
  File "/home/mikkel/apps/NEO/spykeviewer/spykeviewer/ui/neo_navigation.py", line 494, in set_selection
    self.populate_neo_segment_list()
  File "/home/mikkel/apps/NEO/spykeviewer/spykeviewer/ui/neo_navigation.py", line 172, in populate_neo_segment_list
    (self.parent.block_ids[s.block], i)
TypeError: unsupported operand type(s) for +: 'numpy.ndarray' and 'str'


Traceback (most recent call last):
  File "/home/mikkel/apps/NEO/spykeviewer/spykeviewer/ui/neo_navigation.py", line 304, in selected_blocks_changed
    self.populate_neo_segment_list()
  File "/home/mikkel/apps/NEO/spykeviewer/spykeviewer/ui/neo_navigation.py", line 172, in populate_neo_segment_list
    (self.parent.block_ids[s.block], i)
TypeError: unsupported operand type(s) for +: 'numpy.ndarray' and 'str'
```

**Comment by lepmik** [comment]
Hi again, this is not a spykeviewer issue, but from the IO I built - which passed all tests but gave error when running on spykeviewer. The problem was in defining properly supported_objects and readable_objects in the IO.
