### ISSUE TITLE
spykeviewer crashes on startup

### ISSUE THREAD

**Issue by kylerbrown** [rproepp/spykeviewer#13]
Hi, I have the following error on starting spykeviewer.

```
Traceback (most recent call last):
  File "/home/kjbrown/miniconda/envs/spykeviewer/bin/spykeviewer", line 9, in <module>
    load_entry_point('spykeviewer', 'gui_scripts', 'spykeviewer')()
  File "/home/kjbrown/Dropbox/spykeviewer/spykeviewer/start.py", line 42, in main
    from ui.main_window_neo import MainWindowNeo
  File "/home/kjbrown/Dropbox/spykeviewer/spykeviewer/ui/main_window_neo.py", line 21, in <module>
    from .main_window import MainWindow
  File "/home/kjbrown/Dropbox/spykeviewer/spykeviewer/ui/main_window.py", line 33, in <module>
    from spykeutils.plot.helper import ProgressIndicatorDialog
  File "/home/kjbrown/miniconda/envs/spykeviewer/lib/python2.7/site-packages/spykeutils/plot/__init__.py", line 50, in <module>
    from interspike_intervals import isi
  File "/home/kjbrown/miniconda/envs/spykeviewer/lib/python2.7/site-packages/spykeutils/plot/interspike_intervals.py", line 10, in <module>
    from dialog import PlotDialog
  File "/home/kjbrown/miniconda/envs/spykeviewer/lib/python2.7/site-packages/spykeutils/plot/dialog.py", line 29, in <module>
    from guiqwt.signals import SIG_PLOT_AXIS_CHANGED
```

Here are my package versions:

```
guidata==1.7.4
guiqwt==3.0.1
ipykernel==4.1.1
ipython==4.0.1
ipython-genutils==0.1.0
Jinja2==2.8
jupyter-client==4.1.1
jupyter-core==4.0.6
MarkupSafe==0.23
matplotlib==1.5.0
nbconvert==4.1.0
nbformat==4.0.1
neo==0.3.3
numpy==1.10.2
Pillow==3.0.0
pyqtgraph==0.9.7
python-dateutil==2.4.2
PythonQwt==0.5.3
qtconsole==4.1.1
quantities==0.9.0
scipy==0.16.1
spyder==2.3.8
spykeutils==0.4.1
-e git+https://github.com/rproepp/spykeviewer.git@3506e1f646344158bf0ba85b7703bb7bcce6e9a3#egg=spykeviewer-develop
tables==3.2.2
traitlets==4.0.0
wheel==0.26.0
```

**Comment by rproepp** [comment]
Spykeviewer is currently not compatible with the new guiqwt 3.X. I'll
look into it, in the meantime you can just install guiqwt==2.3.1.

**Comment by rproepp** [comment]
Ok, version 0.4.3 (together with spykeutils 0.4.2) is out and compatible with guiqwt 3.

**Comment by kylerbrown** [comment]
Great! Thanks!
